project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - text: Labs
        menu:
          - text: "Lab1: FPGA and MCU Setup and Testing"
            href: labs/lab1/lab1.qmd
      - href: resources.qmd
        text: Resources
            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
