---
title: "Lab1: FPGA and MCU Setup and Testing"
---

Lab Reflection:

This weeks lab was focused on setting up and testing the FPGA and MCU boards that will be used for the rest of the course. This lab 
involved soldering all the necessary components onto the e-155 protoboard, downloading the software interfaces: Lattice Radiant and 
SEGGER Embedded Studio, as well as the simulation software: ModelSim. Demo code was provided to verify that each software and hardware 
component was functioning correctly. Finally, the design part of the lab was to provide a 7 segment led digit display which corresponds 
to its binary input on the protoboard. This design was both simulated and verified with test vectors in ModelSim and was implemented 
with Lattice Radiant.

The most difficult part of this lab by far was debugging each software application so that it would correctly upload to the fpga and 
mcu. The challenges lied in assuring that I had the correct software installed with the correct licenses and the correct hardware 
drivers. On my personal device, I struggled to get Lattice Radiant to synthesize the FPGA and getting SEGGER to drive the MCU remains 
unresolved. Because of these struggles, I had to complete the lab using the computers in HMC's digital lab.

Once the software and hardware appeared to be working enough to get started, I found the verilog module design to be fairly straight 
forward. Calculating the combinational logic for the 7-segment display was the most labor intensive part of the process for me and 
writing the HDL was quite simple. There was minimal debugging of the code, as the majority of the debugging came from understanding how 
Lattice Radiant works. 

This lab also challenged my orginizational skills. This was the first project I have organized using github and learning the nuances 
took some time. 