---
title: "Lab3 Reflection"
description: "Keypad Scanner"
author: "Daniel Fajardo"
date: "9/24/24"
categories:
  - reflection
  - labreport
draft: false
---

This lab was very intellectually challenging for me. The process of understanding how the fsm should function took some time and then 
figuring out how to approach it was more difficult. Once I had a solid grasp, I was able to get the design to work well in simulation in
little time. The speed of development was thanks to implementing testbenches in QuestaSim for the first time in this class, which
allowed for quick debugging.

The frustrating part of this lab came in trying to transfer a design that was working perfectly in simulation into a design that works
in hardware. My first issue came in synthesizing the design in Lattice Radiant. I had inferred a number of latches by not defining each
output in each state in my fsm. By splitting my fsm into multiple fsms in the same module (one for state, nextstate, and others for
outputs), I solved this issue. The next issue came from the button push not registering correctly. In simulation, a button input would
hold the column high, but this was not happening in hardware. I realized that the timing of the column output was not correct and that I
was also getting contention when buttons in multiple rows were pushed at the same time. These issues remained for a while but once I
discovered them, the fix was quick.

After finally getting the design to work in hardware, I felt mostly relief. I felt relief because I had felt like I had total conceptual
understanding of the problem, yet the system was not acting how I expected it to. This lab gave me practice in perseverance and patience.
After about two weeks of working on this lab, I took a few days off, and on the first day back working on it I was able to figure it out.